:sparkles: New FileInfo utility class
PHPCSStandards/PHPCSUtils pull request #572
Opened 2024-03-18 03:54 UTC by jrfnl

This new class initially contains the following methods:
* `hasByteOrderMark(File $phpcsFile): string|false` to determine whether a file starts with a byte order mark and if so, which type of byte order mark.
* `hasSheBang(File $phpcsFile): bool` to determine whether a file starts with a shebang line.

Includes tests.

2024-03-23 14:55 UTC, andrewnicols requested changes
Hi @jrfnl,

This change looks good to me and I believe you cover all of the cases I can think of.

The only thing I have to note is a typo on recognized in the test docblocks `reocgnized`.

2024-03-24 22:16 UTC, jrfnl commented
@andrewnicols Thanks for catching that typo! I've fixed it up in the existing commit now.

2024-03-24 23:39 UTC, andrewnicols approved these changes

2024-05-20 18:05 UTC, jrfnl commented
Rebased without changes. Merging once the build passes.

2024-05-20 18:13 UTC, merged